spring.application.name=desafio-spring-boot

# Perfil activo por defecto (sobreescribir con: -Dspring.profiles.active=prod)
spring.profiles.active=dev

# Server
server.port=8081

# JPA comun
spring.jpa.open-in-view=false

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
