-- crea las tablas iniciales del sistema de gestión de tareas
-- este script es ejecutado automáticamente por flyway al arrancar la aplicación

create table if not exists usuarios (
    id         bigint generated by default as identity primary key,
    username   varchar(50)  not null unique,
    password   varchar(100) not null,
    email      varchar(100) not null,
    role       varchar(20)  not null
);

create table if not exists estados_tarea (
    id          bigint generated by default as identity primary key,
    name        varchar(50)  not null unique,
    description varchar(200)
);

create table if not exists tareas (
    id         bigint generated by default as identity primary key,
    title      varchar(255) not null,
    description varchar(1000),
    estado_id  bigint references estados_tarea(id),
    usuario_id bigint references usuarios(id),
    created_at timestamp    not null,
    updated_at timestamp    not null
);

-- índices para optimizar las consultas más frecuentes
create index if not exists idx_tareas_usuario_id on tareas(usuario_id);
create index if not exists idx_tareas_estado_id  on tareas(estado_id);
create unique index if not exists idx_usuarios_username on usuarios(username);
